### ISSUE TITLE
snap shot of extern class.

### ISSUE THREAD

**Issue by Rickkorsten** [gre/react-native-view-shot#107]
Is t posible to take a snapshot of a view(class) who is not being viewed ?

like this?

`import LaunchView from "./views/launch/LaunchView"`

`
onImageLoadex = () =>
 {
            captureRef(<LaunchView/>, {
            format: "jpg",
            quality: 0.8
}).then
(
            uri => {
                console.log("Image saved to", uri)
                this.setState({ sharePhotoContent: uri, })
            }
);
}
`

**Comment by gre** [comment]
there is a "type" problem here: `captureRef` takes a reference of a React Element, **not** a React Element itself.

if you want to capture a view and not display it, you need to "render it off screen", which can be done by using position absolute and using a high value for `left` . it's a hack but it works.

**Comment by gre** [comment]
There is no way we can solve it otherwise, a React Element have no real view representation until it gets rendered from React. Maybe eventually React 16 will offer a "portal" API and you could have a offscreen mount point to do such thing. but I don't know

**Comment by Rickkorsten** [comment]
@gre thanks for your quick reaction, 

can use like "display:none" instead of "left:100000"?
so basically the user has to see the view before he makes te screen shot and it could not Run in the background?

**Comment by gre** [comment]
I'm not sure what display: none means in context of React Native (does it even exist? maybe it's a recent addition).
the user don't see the view if it's "off screen" by doing the suggested position absolute trick. I've used it in a prod app to do snapshot export & share to social network , it worked well.
maybe later we could introduce a `<Offscreen>` component (I mean technically this could be a RN lib because we could have other usecase of such a thing). but fundamentally you will have to render once in render() and wait that it is loaded.

if you use the `ViewShot ` component this might get easier, something like this should work:


```
  <View style={{ position: "absolute", left: 1000 /* technically you just it to be > screen.width */ }}>
      <ViewShot ref="viewShot" options={{ format: "jpg", quality: 0.9 }}>
        <Text>...Something to rasterize...</Text>
      </ViewShot>
  </View>
```
