### ISSUE TITLE
[Android] Sharing the generated image with a share intent

### ISSUE THREAD

**Issue by sampurcell93** [gre/react-native-view-shot#11]
Hi, maybe this is more a general purpose Android question, but I thought perhaps you could help. Since the uri that is generated for a snapshot only exists in the app cache, passing its uri to a share intent always fails. As soon as I change it to a file saved on external storage, it works. Obviously I'd like to avoid doing this, so I'm looking for other ways to achieve this. More than willing to submit a PR. Thanks!

EDIT: My proposal would be an option like {saveToDisk: true} being passed in which would cause the module to call something like `createPermanentFile` instead of `createTempFile`, but my native Android fu is limited, so there's probably a better way.

**Comment by gre** [comment]
I'm not sure if this should be in react-native-view-shot that should stay minimal.
So currently, the library will put images in a temporary directory that will be cleanup next time the app is opened. I grab the technical from one of RN API (I think it was on ImageEditor).
The problem is if we start introducing other way is we will still have to handle the cleanup and maybe we can't even know. I think it's your (user of the lib) responsibility to copy the image somewhere else , do some stuff with it, and then remove it when you don't anymore need it. You know the best your lifecycle and we probably can't guess it easily.

**Comment by sampurcell93** [comment]
Yeah, that's fair. I'll take a look at doing that, thanks!

**Comment by gre** [comment]
@sampurcell93 please see this change: https://github.com/gre/react-native-view-shot/commit/a85cf9629af6ee27350f1c78084b8ec58eae4134

the string returned by the lib used to be like `file:/data/user/0/...` but is now `/data/user/0/...`.
So in previous version of the lib, `new File("file:/...")` was not working. It was probably the reason you had an issue (the file is not deleted, it's simply wrong path in the lib), but now it should work.

**Comment by gre** [comment]
that said, you probably still will have to copy somewhere else, not because the file is deleted but because the file is in a private place ATM. not accessible from external (so not from an Intent).

```
public void copy(File src, File dst) throws IOException {
        FileInputStream inStream = new FileInputStream(src);
        FileOutputStream outStream = new FileOutputStream(dst);
        FileChannel inChannel = inStream.getChannel();
        FileChannel outChannel = outStream.getChannel();
        inChannel.transferTo(0, inChannel.size(), outChannel);
        inStream.close();
        outStream.close();
    }

    public File copyToPublic (File input) throws IOException {
        File dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);
        dir.mkdirs();
        File out = new File(dir, input.getName());
        copy(input, out);
        return out;
    }
```
