### ISSUE TITLE
screenshot is displaying blank for a FlatList

### ISSUE THREAD

**Issue by lohaniabhishek** [gre/react-native-view-shot#113]
- I have a `FlatList` inside a `View`. When taking the screenshot every thing is coming out to be correct except for the `FlatList`. Its displays nothing where the `FlatList` should be.

- Even when the `FlatList` is at the root, the behaviour is still the same.

- Plus `FlatList` doesn't allow for `snapshotContentContainer `

**Comment by klawdyo** [comment]
Me too

**Comment by gre** [comment]
- which OS? iOS or Android?
- have you tried to set `collapsable={false}` on the FlatList prop?
- for snapshotContentContainer, i'm not sure what can be done because ultimately `FlatList` controls how much content it's going to render and we can't force it. So if you need to capture a long list of contetn, you would have to use a ScrollView implementation.

**Comment by Norcy** [comment]
You can use `initialNumToRender` and `windowSize` to avoid blank or content missing

```js
<FlatList
  initialNumToRender={999}
  windowSize={999999}
  ...
/>
```
