### ISSUE TITLE
[Question] Can this library record a video of the screen instead of a Snapshot?

### ISSUE THREAD

**Issue by Eyesonly88** [gre/react-native-view-shot#132]
### Question

Can this library record a video of the screen instead of a Snapshot. Also, is there any other library that can do record the screen?

Thanks.

**Comment by gre** [comment]
Hi @Eyesonly88 , this is out of scope of this library, however I think it is technically possible but I don't know any library for this. I did something kinda similar (react-native-webgl-view-shot) but it's targeting WebGL, not a video. If I find time for this, I can start a new library, otherwise you can try yourself ;) cheers

**Comment by mikaello** [comment]
[ReactRecorder](https://github.com/vinceyuan/ReactRecorder) is a react-native module for recording the screen.

If only Android is of concern, wrapping [Telecine](https://github.com/JakeWharton/Telecine) seems like a good bet.

**Comment by Eyesonly88** [comment]
@mikaello wow thank you so much! This is exactly what I needed 🙇

**Comment by JanOwiesniak** [comment]
@Eyesonly88 @mikaello [react-native-screen-recorder](https://github.com/ycswaves/react-native-screen-recorder) could be an interesting alternative as well, it's influenced by [ReactRecorder](ReactRecorder) and the example app works great in the iOS simulator.

The problem here: It has [performance issues](https://github.com/ycswaves/react-native-screen-recorder/issues/2) when it runs on a real device.

@Eyesonly88 have you found a performant solution to accomplish a screen video yet?

Maybe someone here knows a solution to the mentioned [performance issues](https://github.com/ycswaves/react-native-screen-recorder/issues/2)?
