### ISSUE TITLE
How to store the screenshot?

### ISSUE THREAD

**Issue by rohitgoyal** [gre/react-native-view-shot#18]
Is there anyway to store the screenshot to Phone's camera roll/gallery instead of the tmp directory?

**Comment by gre** [comment]
you can look at RNFS is the current answer. maybe it should be in the lib as it seems to be a common requested feature, even though I would prefer to keep the lib simple.
I accept PRs

**Comment by fantapop** [comment]
By the way, it looks like RNFS is getting deprecated:

https://github.com/johanneslumpe/react-native-fs/issues/228

**Comment by gre** [comment]
I guess we might reconsider making this a built-in feature then. user should be able to tell where he wants the image to be. one problem I see is if we use an absolute path, it will be platform dependent. I'm not sure if RN have a solution to abstract that yet. (actually I wish basic op like moving a file would be available in RN)

**Comment by gre** [comment]
we could start with a basic boolean, but I'm sure people will then ask that they want the screenshot to go in a specific folder / photo album for instance.

**Comment by fantapop** [comment]
It occurs to me that if the user wants a cross platform save they will have
to figure out how to choose a different path for android vs iOS as it is.
Anyway to make that easier would be welcome. It looks like
react-native-fetch-blob handles that problem by predefining some variables
with base paths in them for the user to use.

https://github.com/wkh237/react-native-fetch-blob/blob/master/README.md#user-content-dirs

It probably wouldn't be terrible to just pull in react-native-fetch-blob as
a dependency for handling this. Or giving some example of the rename code
might be just as good.

Chris

On Mon, Feb 27, 2017 at 12:57 AM Gaëtan Renaudeau <notifications@github.com>
wrote:

we could start with a basic boolean, but I'm sure people will then ask that
they want the screenshot to go in a specific folder / photo album for
instance.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gre/react-native-view-shot/issues/18#issuecomment-282662507>,
or mute the thread

**Comment by gre** [comment]
I have implemented something in branch `dirs`.
it works but what's weird (to me) is when I set `path: dirs.PictureDir+"/foobar2.png"` , on iOS it ends up being a folder under the app directory but not the user picture dir..mmh. and I'm not seeing it in the Photos app. same happen for Android.
not sure what's wrong

**Comment by fantapop** [comment]
I don't see any obvious issues.  I might have time this evening to try and run it if you don't figure it out.

**Comment by fantapop** [comment]
It seems to be working for me.  I made these changes to App.js in your example:

```
$ diff -u App.orig.js App.js
--- App.orig.js 2017-02-28 22:50:03.000000000 -0800
+++ App.js      2017-02-28 22:46:36.000000000 -0800
@@ -12,7 +12,11 @@

 } from "react-native";
 import omit from "lodash/omit";
-import { takeSnapshot } from "react-native-view-shot";
+
+import { takeSnapshot, dirs } from "react-native-view-shot";
+
+// cross platform dirs:
+const { CacheDir, DocumentDir, MainBundleDir, MovieDir, MusicDir, PictureDir } = dirs;

 import Btn from "./Btn";

@@ -33,16 +37,20 @@
   };

   snapshot = refname => () =>
-    takeSnapshot(this.refs[refname], this.state.value)
-    .then(res =>
-      this.state.value.result !== "file"
-      ? res
-      : new Promise((success, failure) =>
-      // just a test to ensure res can be used in Image.getSize
-      Image.getSize(
-        res,
-        (width, height) => (console.log(res,width,height), success(res)),
-        failure)))
+    takeSnapshot(this.refs[refname], {
+        ...this.state.value,
+        path: dirs.PictureDir+ '/hi.jpg'
+    })
+    .then(res => {
+      console.log("Image saved to", res);
+
+      return this.state.value.result !== "file" ? res : new Promise((success, failure) =>
+          // just a test to ensure res can be used in Image.getSize
+          Image.getSize(
+            res,
+            (width, height) => (console.log(res,width,height), success(res)),
+            failure));
+    })
     .then(res => this.setState({
       error: null,
       res,
```

Then checked in the console output:

<img width="1017" alt="screen shot 2017-02-28 at 10 47 15 pm" src="https://cloud.githubusercontent.com/assets/6658984/23448810/03c398ac-fe08-11e6-9a6c-9d04f30c8ae0.png">

**Comment by gre** [comment]
yeah, it works, but can you see the picture when you browse the Photos app then? Because I can't.
Maybe I'm expecting it would but it's not supposed to show up there?

It seems to store it inside the `/data/Containers/Data/Application/*/Pictures` but I would expect it would store it more in like next to the camera roll / in an album. But maybe i'm just mistaken. it looks like iOS also have a `UIImageWriteToSavedPhotosAlbum` also.

(The initial request of this issue was "store to camera roll / gallery".)

**Comment by gre** [comment]
or like http://stackoverflow.com/questions/4457904/iphone-how-do-i-get-the-file-path-of-an-image-saved-with-uiimagewritetosavedpho/4458451#4458451

**Comment by fantapop** [comment]
I understand what you want to do. I'm not an expert but I think you need to
use a special Api to save something to the camera roll. It's slightly
trickier because you need the users permission to save images there since
its out of the sandbox.

**Comment by gre** [comment]
I think you are right and I'll consider this to be out of scope of the library (if you need to save in cameraroll / album, use a lib that do that)

I'll just merge my branch that allows to save the captured image to an absolute path (e.g. to the app's namespace folders like Document or Pictures) – you can then still retrieve it to save it somewhere else with a native module / another lib.

**Comment by xuetongiqn** [comment]
you can try this: https://developer.android.com/reference/android/content/Intent.html#ACTION_MEDIA_SCANNER_SCAN_FILE

**Comment by Piyush132000** [comment]
hlo friends i am working on my college project , please help me i want to take a screen shot of specific part of screen  like card part and then store the screen shot to image folder of project please help me .
