### ISSUE TITLE
return a black screen when convert canvas to image

### ISSUE THREAD

**Issue by shan1iu** [gre/react-native-view-shot#189]
**Platform:**  Android
#### Expected behavior
screenshot of canvas

#### Actual behavior
return a black screen

#### In my render() method
```
<ViewShot ref="viewShot" options={{ format: "jpg", quality: 0.9, result: "base64" }}>
    <View collapsable={false}>
        <Canvas ref={this.mycanvas} style={{ width: deviceWidth, height: canvasHeight }} crossOrigin="Anonymous" 
        />
     </View>
</ViewShot>
```

#### method to capture

```
this.refs.viewShot.capture().then(uri => {
    console.log("do something with ", uri);
}
```

**Comment by sobanarshad85** [comment]
repalce your format jpg to png or any other and it's done

**Comment by dean9703111** [comment]
I try to screen shot include canvas, but it is  still empty

**Comment by sobanarshad85** [comment]
@dean9703111 add any background color.and good to go.
Backgroundcolor could be any one eother black or white no issue

**Comment by gre** [comment]
it really depends when you call that capture() but you probably need to wait a bit longer because `react-native-canvas` works with a webview and it takes longer to load so you need to wait it fully loaded and drawn.

apart from that, it should probably work as proven by `example/src/Canvas.js`

<img width="476" alt="Capture d’écran 2019-08-11 à 12 40 26" src="https://user-images.githubusercontent.com/211411/62829840-f2255480-bc02-11e9-9957-0e3c53efc665.png">

**Comment by obiwankenoobi** [comment]
@gre the example work with ios but never worked with android. :(

**Comment by obiwankenoobi** [comment]
@dean9703111 found a solution
