### ISSUE TITLE
can i capture user  screen capture？

### ISSUE THREAD

**Issue by Tomatoo** [gre/react-native-view-shot#19]
if i can capture user screen capture, it will be perfect.

thanks!

**Comment by gre** [comment]
You can snapshot the root View maybe? Or do you need a full window shot including the status bar?

**Comment by myoula** [comment]
i need a full window shot including the status bar. how to do?

**Comment by gre** [comment]
if it's technically possible I would be happy to add this in react-native-view-shot.

PR welcomed.

**Comment by myoula** [comment]
I resolve it in the ios, with this code:
`UIScreen *mainScreen = [UIScreen mainScreen];
    UIView *view = [mainScreen snapshotViewAfterScreenUpdates:TRUE];
    UIGraphicsBeginImageContext(view.bounds.size);
    BOOL success = [view drawViewHierarchyInRect:view.bounds afterScreenUpdates:YES];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();`

**Comment by myoula** [comment]
i found and resolve it by this https://github.com/daydreamboy/WCScreenshotHelper

**Comment by gre** [comment]
nice. could be interesting to have this in the lib so let's keep it open.

**Comment by gre** [comment]
what would be nice is allowing to not provide the first param (no view to capture) would mean to capture the screen.

**Comment by gre** [comment]
**iOS**: after investigating a bit and according to http://stackoverflow.com/questions/8508428/capturing-full-screenshot-with-status-bar-in-ios-programmatically#comment39460916_8509534 , it does not seem possible you can capture the full screen **including the status bar** . I guess this is a security issue because it's something outside the app.
@myoula am I wrong? did you succeed to have a full screenshot with the status bar?

**Android**: to be investigated.

**Comment by gre** [comment]
as this is not trivial, I'll consider this out of scope of this library, `react-native-view-shot` have `view` in it – to snapshot user's screen make a new library ;)
