### ISSUE TITLE
When capture a image by screenshot it will reduces height automatically for every repeated process

### ISSUE THREAD

**Issue by pluvd7j** [gre/react-native-view-shot#228]
#### Version & Platform
Android (not tested on IOS yet)
RN 0.58.5
React 16.6.3
ViewShot 2.6.0 

```bash
<ViewShot style={{ flex:1, backgroundColor: "#fff",alignContent: 'center' }} ref="viewShot" options={{ format: "jpg", quality: 1.0}}>
  <View style={{ position: "absolute"}}>
    <View>
      <TouchableHighlight onPress={evt=> this.handlePress(evt)}> 
      { this.state.externalImage == null ?
        <Image source={this.state.localImg} 
               resizeMode={ "stretch"} 
               style={{ width:Dimensions.get( 'window').width, height: Dimensions.get( 'window').height}}
               /> :
        <Image source={{uri: `data:image/png;base64,${this.state.externalImage}`}} 
               resizeMode={ "stretch"} 
               style={{ width: Dimensions.get( 'window').width, height: Dimensions.get( 'window').height}}
               /> 
      }
      </TouchableHighlight>
    </View>
  </View>
</ViewShot>
```

#### Expected behavior
Need to  capture actual size of the image

#### Actual behavior
Reducing height from the original image for every repeated process

**Comment by gre** [comment]
i'm not really understanding what the issue is. could you reduce the example to a minimal report of the problem?

When you capture into an image, you get a bigger image because it's in pixel dimension and not in point dimension, so there is a ratio (that correspond to the device pixel ratio). It sounds like you fall into something that is expected? (unless i misunderstand something)
