### ISSUE TITLE
How can I save an image with transparency?

### ISSUE THREAD

**Issue by jordangarvey** [gre/react-native-view-shot#235]
I’m trying to render a basic View with a border radius inside the ViewShot component (`<ViewShot options={{ format: "png" }} ref="templateItem">`), but the saved image in the camera roll has a white background. Is it currently possible to save an image with transparency?

**Comment by gre** [comment]
I don't think this issue is on `react-native-view-shot` side. probably the cameraroll / lib you are using is adding the white color and does not support transparency?

Proof that it's not a problem on this lib side:

https://github.com/gre/react-native-view-shot/blob/master/example/src/Transparency.js

this example implement screenshotting a rounded rectangle and putting it back into an `<Image>` on top of a background color. It properly works with defaults (which uses PNG)


<img width="453" alt="out" src="https://user-images.githubusercontent.com/211411/62818136-17528e00-bb43-11e9-8fce-ad170cacb26d.png">

**Comment by Tranthanh98** [comment]
the reason is format jpg, change to png and it works
