### ISSUE TITLE
Can not take screenshot with react native camera on ios

### ISSUE THREAD

**Issue by viralS-tuanlv** [gre/react-native-view-shot#250]
How can i take a shot with rncamera on ios, i try on android work perfect, but ios just a black screen when i take a shot. Have any PR to fix it? thanks

**Comment by Taym95** [comment]
I'm just curious, why you would like to take a snapshot of a camera and not returning picture from rncamera directly?

**Comment by viralS-tuanlv** [comment]
> I'm just curious, why you would like to take a snapshot of a camera and not returning picture from rncamera directly?

Because i am using rncamera for recoginze face, and if i am using take picture of rncame ra it very slow and heavy size, on android, i used to view shot and very fast and good, so i want to use take screenshot instead take picture of rncamera

**Comment by wcandillon** [comment]
@gre I'm having a similar issue/use case. Is the solution to pipe the camera input into a GLView? Something similar to https://github.com/gre/gl-react/blob/master/examples/expo-gl-react-camera-effects/src/GLCamera.js ?

**Comment by AideProjet** [comment]
Hi, did anyone found a solution for this ?

Thanks,

Théo

**Comment by gre** [comment]
I think if react-native-view-shot can't capture the pixels (and renders black instead) which happens inconsistently between iOS and Android, there is a low chance we can solve it from this library and I would look more at what the initial library (react-native-camera) offers in term of capturing the camera content.

It seems there is a method `takePictureAsync` which is probably what you need to use for now.

If the usecase to use react-native-view-shot was because of compositing/rendering some effects on top of it, I would suggest to look either at react-native-webgl (if you can write it in GL) or simply have an intermediary <Image> and snapshot that, or even writing custom native code to do what you need.
