### ISSUE TITLE
How to get bmp image?

### ISSUE THREAD

**Issue by panda919** [gre/react-native-view-shot#255]
I gonna get bitmap file.
But I can not find bitmap option on this plugin.
How to get bmp file?

**Comment by gre** [comment]
If I understand correctly, you want this library to support the .bmp format?
I'm not sure to understand why but .png is much more recommended and is more compressed.

I'm going to consider this is out of scope of this library because it does not seems to be something that ios/android would support. If you manage to make it work without any extra library I would happily accept a PR tho.
