### ISSUE TITLE
Is it possible to screenshot behind the scene? 

### ISSUE THREAD

**Issue by minmingsheng** [gre/react-native-view-shot#256]
Is it possible to screenshot behind the scene? render a view but hide it on screen, then screenshot on that hidden view...? doable by any chance...?

**Comment by HiteshGunwant** [comment]
yes just use position absolute property and apply ref

**Comment by tuur155** [comment]
I would also like to capture a view before the user can see it. My use case is that I want to capture a grid when its rendered -> take a screenshot -> replace the screenshot with the grid so performance when navigating is better. I have succeeded in doing this but the problem is that the user sees a white flash when the screenshot is taken. Could you elaborate some more about how to do capture a screen without the user seeing this.

**Comment by 592da** [comment]
any example please ?

**Comment by gre** [comment]
```
const OffscreenViewShot = ({ width, height, ...rest }) => (
  <ViewShot {...rest} style={{ width, height, position: 'absolute', right: -width - 5 }} />
);
```

you can use position absolute to move your snapshotting view outside of the visible area.

as shown in this example: https://github.com/gre/react-native-view-shot/blob/master/example/src/Offscreen.js#L8-L10
<img width="372" alt="Capture d’écran 2020-01-19 à 14 47 26" src="https://user-images.githubusercontent.com/211411/72682172-9ffa3080-3aca-11ea-8e34-15b7354fa50c.png">


feel free to adapt to your needs but that's the concept and it should work.

**Comment by babyrusa** [comment]
@gre  Hi does this still work? The example link was removed

**Comment by babyrusa** [comment]
Found the new example link https://github.com/gre/react-native-view-shot/blob/master/example/Example/src/Offscreen.js
