### ISSUE TITLE
How to save the captured image in with 90 degree rotation?

### ISSUE THREAD

**Issue by ajay2c9** [gre/react-native-view-shot#277]
Hi,
I'm using the react-native-view-shot in my project. I want to rotate the image while saving. how to implement the image rotation in the view shot after capturing the screen without using any extra modules.   
Please give suggestions.

Thank you.

**Comment by Vavassor** [comment]
I have the same need in the project I'm working on.

The page with the `ViewShot` component is displayed and used as though it's in landscape mode. But for various reasons it's actually in portrait mode on android. So when it saves the image, the writing and image are sideways.

For the moment, we're rotating the image with another library after receiving it from the capture function. Luckily, we're saving it as `.png`, because re-saving a `.jpg` would introduce quality loss. It does mean a second trip back through reading and saving the file, though.

**Comment by ajay2c9** [comment]
Hi **@Vavassor**,
Is there any possibility to rotate the image without using other modules?

**Comment by gre** [comment]
I think this is beyond this module. I think instead it should be the scope of a library like https://github.com/react-native-community/react-native-image-editor (which btw used to be built-in in react-native so I think you can expect such lib to be well maintained too)

**Comment by Vavassor** [comment]
We ended up writing a native module of our own to do the rotation. That image editor package probably would've been a fine solution too.

**Comment by kostas64** [comment]
I would have a different approach. Why not to use react native for that? If you don't want result to be visible, you can have a hidden copy of the components translated outside of screen and capture screenshot from that
