### ISSUE TITLE
Wrong resolution for output

### ISSUE THREAD

**Issue by vmenekos** [gre/react-native-view-shot#291]
Viewshot capture has different size than set in options
Platform android.
iOS working good.

**Comment by FrederickEngelhardt** [comment]
Noticed this as well.

**Comment by gre** [comment]
Do you have an example? This is clearly explained and documented in readme that the size you provide is in virtual point and not in pixels. It is multiplied by the pixel ratio of the device

**Comment by brunowbbs** [comment]
Could you give us an example?

**Comment by mickeylam** [comment]
For Android, I think it must not use the "virtual point" for the size in options. Because the Javascript has precision issue. 
For example, I want a image 240X240. For now, I have to use 240 / PixelRatio.get() as a value in options.
And the final result will be 239X239, because in Javascript, (240 / 2.75 * 2.75) = 239.99999997
In the RNViewShotModule.java, 
`Integer width = options.hasKey("width") ? (int)(displayMetrics.density * options.getDouble("width")) : null;`
which cause the problem.

**Comment by gre** [comment]
Ok thanks for pointing it out, indeed it seems to be a mistake that a `scaleWidth` is used in RNViewShotModule.java. I will need help on identifying if it's also a problem in iOS or if we are exact on iOS. then I think we can provide a fix.

**Comment by gre** [comment]
https://github.com/gre/react-native-view-shot/pull/414 should fix it. feel free to review. will be in a future release (breaking).
