### ISSUE TITLE
captureScreen() dosen't capture fully?

### ISSUE THREAD

**Issue by enigmablue** [gre/react-native-view-shot#308]
I'm trying to capture my whole screen using captureScreen()

![image](https://user-images.githubusercontent.com/35584085/86308072-e2fc2a80-bc4a-11ea-8f3d-cebeaded3ce4.png)

But all i get is the background. 
Any idea?

![image](https://user-images.githubusercontent.com/35584085/86308119-f27b7380-bc4a-11ea-8a6f-6c3a8fc9dbac.png)

My container is coded like this
```
  contentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0007',
    position: 'absolute',
    top: 0, left: 0,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    zIndex: 100000
  },
  container: {
    height: hp('45%'),
    width: 300,
    backgroundColor: "#fff",
    padding: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },

```

**Comment by enigmablue** [comment]
i tried using a react native elements overlay instead
```
  <Overlay
      isVisible={hasError}
      onBackdropPress={()=>props.setError(null)}
      overlayStyle={
        {
          padding:0,
          backgroundColor:'white',
          width: wp('50%'),
          height: hp('50%')
        }
      }
      fullScreen = {false}
      animationType={'slide'}
    >
```

But got a blank white screen instead :(

**Comment by yalcinozer** [comment]
@enigmablue I think its about your viewshot component wraps your dialog or not. Please make sure your dialog(modal) component PLACED in viewshot component.

**Comment by enigmablue** [comment]
i tried to place it in the highest level and it still didn't get it to work earlier.
Maybe i'd try to reproduce it in a very simple new code base

**Comment by Crhaj** [comment]
Was there any progress or any workaround?

**Comment by Moji0098** [comment]
i have this problem!! :((

**Comment by ashfurrow** [comment]
I was having this problem and fixed it (at least on iOS) by modifying this line:

https://github.com/gre/react-native-view-shot/blob/926cadad25e72fe0c883a2f350de9de7ea08341a/ios/RNViewShot.m#L56

The problem here is that we're accessing the `rootViewController` property of `UIWindow`, which would not include modally-presented view controllers on top of it. Rather, we should be treating the `UIWindow` _as_ the view we want to snapshot itself.

```diff
-     view = window.rootViewController.view;
+     view = window;
```

I've verified this works on iOS but I'm still exploring this on Android. I hope this helps someone in the meantime.

**Comment by jianxinzhoutiti** [comment]
android modal user captureScreen(). Screen no modal View
