### ISSUE TITLE
A few Questions

### ISSUE THREAD

**Issue by flaviotobi** [gre/react-native-view-shot#33]
Hi there, first thing thanks very much for your hard work on this project :)

I would like to know if there is a way to take a snapshot without passing the ref, and i'm asking this because to get the ref (correct me if i'm wrong) you need to render the element, and that's my problem, i have to create images of  about 80 views. as you understand this is a performance killer.

If you believe it's possible to make this in some way.
 i'm very interesting to know your toughs's on this one. 

in the native code side i was think something like this:
Pass to bridge Component and props-->In the Native side call react-native method to create the View in the background--> create a image of the view --> return path

All this procedure made with multi threading support.

Attention, i never create a native module for react-native, it's probably that i said something stupid above.

This issue is to know if Its possible to do, if you can do it, and if you can't , if you could assist me to do it.

**Comment by gre** [comment]
I'm not sure what you mean by "without passing a refer" ?

Can you tell me what would be the signature of such a function? Currently it's basically `(ref: ReactRefObject) => Promise<string>`

**Comment by flaviotobi** [comment]
For example passing the component it self like: 
<View style={{flex:1, backgroundColor:'red'}} />

**Comment by gre** [comment]
so basically you want

```
(elementAkaJSX: React.Element) => Promise<string>
```

?

I don't think we can make it more optimize than rendering once, getting a ref, and rasterizing it, because `<View />` is something that only exist on JS side and will have to be resolved on this side. It will  trigger some 'native element' creation through bridge, and only when that is done, we can call the native code to snapshot that..

related to that question, see my answer here: https://github.com/gre/react-native-view-shot/issues/31#issuecomment-274050475

maybe more thoughts need to be given into this to provide an elegant API, but I don't think we'll be able to do more efficient things. That said, if you need to render 60 different views, you might want to try to parallelize this work (render all in once, OR maybe 10 at a time. I guess you need to try and see what is the best perfs)

BTW, the react-native-view-shot implementation already should happen asynchronously and should not take time on the UI thread. if it does, it's probably a bug. However, this is probably not true for Android according so this PR: https://github.com/gre/react-native-view-shot/pull/28 . unfortunately I had to close this PR because the code was not working when I tested, PR is welcomed to fix that state

**Comment by flaviotobi** [comment]
Yes, my  thought was to pass the "component" to native side, see what function react native use to create <View> component in the native side and use it.

My problem is not the react-native-view-shot, it's the need to render the view to use it.
As you said above i will try with just one render create all the Views and take the snapshot's :)
(Fingers cross xD)

I believe we can close this now :)

**Comment by gre** [comment]
I don't think there is a difference between "passing component to native side, create component and use it" and "rendering the view".

you need to render the view to rasterize it. the only different might be to not actually "showing it to screen" but I don't think there are big perf issue with or without doing that. (maybe i'm wrong?)

thanks
