### ISSUE TITLE
iOS expo-camera support?

### ISSUE THREAD

**Issue by alenmestrov** [gre/react-native-view-shot#377]
Hi,

Is it possible to use react-native-view-shot with expo-camera in iOS? 

For example, like this:
               <ViewShot style={{ flex: 1, backgroundColor: "transparent" }}
                    onLayout={(res) => { this.setVariables(res.nativeEvent.layout); }}
                    ref={ref => { this.imageContainer = ref; }}>
                    <Camera style={{ flex: 1}}
                        ratio={this.state.ratio}
                        pictureSize={this.state.pictureSize}
                        type={this.state.cameraType}
                        ref={ref => { this.state.camera = ref; }}
                        onCameraReady={ () => { if(this.state.pictureSize == null) { this.setupPictureSize(); }}}>
                    </Camera>
                </ViewShot>

Thank you very much in advance.

**Comment by gre** [comment]
It's probably not supported at the moment and it would be wiser to have the "expo-camera" itself providing a way to "capture" on the camera component itself, because snapshotting the View that is produced by the camera won't be the best quality & can easily be broken if the rendering implementation changes.

**Comment by gre** [comment]
i'm not sure if something got improve on this area but your best chance is to have the camera library solve it for you (like getting an image of the camera) rather than screenshoting the component because sometimes tends to break regarding the "snapshotability" of the resulting rendering output of these library.
