### ISSUE TITLE
Capturing custom native module

### ISSUE THREAD

**Issue by dfrl-dev** [gre/react-native-view-shot#425]
Am I misunderstanting, or is it impossible to capture a custom/complex view?

I've implmented a native component for a piece of camera hardware, and I'd like to capture a thumbnail, but can only seem to get blank white images.

Is the interoperability table the hard and fast list of supported views?

**Comment by gre** [comment]
it may or may not working depending on if the underlying technology allows to be captured with the current approach we have.
respectively:
- on iOS: 
  - either renderInContext https://github.com/gre/react-native-view-shot/blob/master/ios/RNViewShot.m#L113
  - or drawViewHierarchyInRect https://github.com/gre/react-native-view-shot/blob/master/ios/RNViewShot.m#L118
- on Android:
  - using Bitmap https://github.com/gre/react-native-view-shot/blob/a990eeda889fbb8316693b55581838e97398caf2/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java#L372


Then, there are two possibilities to solve a view that wouldn't be captured:
- contribute to the library to add one more way to capture it in the library code
- ask the feature directly on the other library you use. For instance, if it's a Video library, they might better offer you directly the way to get a video frame instead of having to use this library (which aim to capture the view as displayed)



Thanks
