### ISSUE TITLE
Can't get Image to show

### ISSUE THREAD

**Issue by oakis** [gre/react-native-view-shot#52]
This is what i get when running my script:
"file:///data/user/0/com.coach/cache/ReactNative-snapshot-image1317300113.png"

When i put it like this:
`<Image source={{uri: uriAbove }} />`
it shows nothing.

When i put it like this:
`<Image source={require(uriAbove)} />`
react-native crashes with error:
Unknown named module: 'file:///data/user/0/com.coach/cache/ReactNative-snapshot-image1317300113.png'

Any idea what I can do about it?

**Comment by gre** [comment]
`require` is not going to work as it's for compile-time requiring a local file (from your source code).

that `<Image source={{ uri }} ..` should work tho, i'm using it in https://github.com/gre/react-native-view-shot-example/blob/master/App.js#L114 – **can you try to define a `style={{ width, height }}` because i'm not sure `<Image>` will render anything if you don't define width / height.**


also:
do you attempt to do that `<Image>` just after doing a snapshot? You don't close the app between the snapshot and the `<Image>` rendering? (it's a temporary file – you might try to place it somewhere else like explained in https://github.com/gre/react-native-view-shot#dirs-constants )

**Comment by oakis** [comment]
Thank you so much!! I've been trying to do this with `<Image width="" height="" />` instead of `<Image style={{width: num, height: num}} />` this entire time. Such a simple solution..
