### ISSUE TITLE
Take snapshot, when Component is ready

### ISSUE THREAD

**Issue by timLoewel** [gre/react-native-view-shot#54]
Part of my snapshot is an `Image`, which is fading in, when the image is loaded and displayed the first time. When I take a snapshot, while the image is still not completely displayed, I get a grayed out image.

**Is there a way to trigger the snapshot, when the `View` is ready and rendered completely?**

What I am currently doing is trigger the snapshot with `onLayout` of the outer `View` and a relatively long timer, that waits another second, before the snapshot is taken. But that is making my app less responsive and sometimes the image is still not there, when the snapshot fires. I tried `onLoad` and `onLayout` of the `Image`, but those did not work any better.

Any Idea?

Thanks, Tim

**Comment by gre** [comment]
the library won't solve that because it's too complex. and actually there is no way the native code can check that a "component is ready". (nor on the JS side, because there is no universal convention for 'waiting a component to be ready').

so IMO, the best for you is to trigger the snapshot at the right time, at the right lifecycle, in the right callback / maybe after a delay.
For images, `onLoad` is a right callback to look at.
But yeah, if you have fading, maybe you want to disable it `<Image fadeDuration={0}`  – or you can add-up a timeout for that..

**Comment by timLoewel** [comment]
Thanks a lot for your help. I guess, I will have to make do with the timeout.
