### ISSUE TITLE
Iphone save picture error

### ISSUE THREAD

**Issue by xuanheScript** [gre/react-native-view-shot#66]
Simulator is effective to save, iphone will be prompted on the authority

**Comment by xuanheScript** [comment]
![image](https://cloud.githubusercontent.com/assets/19216775/26300803/c6364688-3f11-11e7-8a6f-2c87d5b12383.png)

**Comment by xuanheScript** [comment]
This is the code
![image](https://cloud.githubusercontent.com/assets/19216775/26300842/e326ae72-3f11-11e7-930a-fbfa72f235e7.png)

**Comment by xuanheScript** [comment]
@gre 需要你的帮助，Need your help, thanks

**Comment by gre** [comment]
sounds like it's a permission issue.

Do you really need to save it to PictureDir ? `path` is an advanced feature and i'm not sure i got it right. but takeSnapshot should work if you don't provide a `path`, it will be a temporary file but you can use its URI to do things like sharing. (via http://facebook.github.io/react-native/docs/actionsheetios.html for instance )

**Comment by xuanheScript** [comment]
Sorry, I really need to save to the phone album, I use the react native 0.43, I do not know if this is related, but also can provide some other help?

**Comment by gre** [comment]
sorry but this is a bit beyond my knowledge on the subject, I added a disclaimer on the `path` usage and I can't guarantee it works nor to provide any help on that, sorry :'(

I even think this `path` feature should not be in the lib because it's a complex topic beyond the scope of this library that "snapshot a view":
I feel this problem of moving a file to a given place with "intent" & permissions should be solved by a more generic react-native library. maybe something like https://github.com/itinance/react-native-fs would do that? Would that solve the problem?

thanks

**Comment by xuanheScript** [comment]
@gre Very happy i solved this problem using CameraRoll successfully saved pictures that i have not tested yet android but i hope it can help to someone else.
![image](https://cloud.githubusercontent.com/assets/19216775/26347889/87cf94cc-3fdd-11e7-8b9b-c0482d1b5b79.png)

**Comment by gre** [comment]
oh great!
