### ISSUE TITLE
[QUESTION] Resolution

### ISSUE THREAD

**Issue by Gigasz** [gre/react-native-view-shot#93]
Is the resolution of the picture limited by the device's screen resolution or if there is a image with higher resolution in the view it will be the same resolution as the image?

**Comment by gre** [comment]
The captured image is the View bounds in real pixels.

It's technically possible to do a big off-screen view in React Native. like `<View style={{ width: 4000, height: 3000 }} />` is going to be a 8000x6000 on a retina device (x2). So technically you **can** snapshot any possible resolution.

In practice however, there are limitation, usually depending on the platform/device. For instance, on Android I've previously experienced issue when trying to capture views that are bigger than the  device screen **area** *(meaning that: imagine you have a phone of screen size 500x1000, meaning 500'000 pixels , you can't capture 510x1000 because it overflows, however you was able to capture things like 600x600 because it's lower than 500'000)* – **however** i'm not sure it's true anymore, in the current implementation. I guess best is to try it out for your usecase
